---
abstract: 'a maniac download accelerator.'
author:
  - 'Shlomi Fish <shlomif@cpan.org>'
build_requires:
  File::Spec: 0
  File::Temp: 0
  IO::Handle: 0
  IPC::Open3: 0
  Module::Build: 0.3601
  Test::More: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.009, CPAN::Meta::Converter version 2.132830'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-ManiacDownloader
requires:
  AnyEvent::HTTP: 0
  Fcntl: 0
  File::Basename: 0
  Getopt::Long: 2.36
  JSON: 0
  List::Util: 0
  List::UtilsBy: 0
  MooX: 0
  MooX::late: 0.007
  URI: 0
  autodie: 0
  perl: 5.012
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=App-ManiacDownloader
  repository: ssh://hg@bitbucket.org/shlomif/perl-App-ManiacDownloader
version: 0.0.7
